name: Prod - Create and publish Docker backend

on:
  push:
    branches: ["main"]
    paths:
      - "apps/backend/**"
      - ".github/workflows/docker-publish-production.yaml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/charlesjudith/winnieswap-backend

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lowercase Repository owner
        id: repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ env.REPO_OWNER }}/winnieswap-backend

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./apps/backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER }}/winnieswap-backend:production
